- is_full_depth: 'True'
  manufacturer: ASRock Inc.
  model: IMB-1213
  slug: asrock-imb-1213
  u_height: 0
- is_full_depth: 'True'
  manufacturer: Flex, LTD
  model: 9U Locker
  slug: 9u-locker
  u_height: 9
- is_full_depth: 'True'
  manufacturer: Juniper Networks, Inc
  model: QFX5120-48Y-8C
  slug: qfx5120-48y-8c
  u_height: 1
- manufacturer: Vapor, IO
  model: VEC Cartridge Rev 3.0
  part_number: '700747'
  slug: vec-cart-v3
  u_height: 0
